import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Charm, Domine } from "next/font/google";
import "./globals.css";
import Header from "./header/header";
import Footer7 from "./footer/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const charm = Charm({
  variable: "--font-charm",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const domine = Domine({
  variable: "--font-domine",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${charm.variable} ${domine.variable} antialiased relative`}
      >
        <Header />
        <main className="mt-16">{children}</main>
        <Footer7 />
      </body>
    </html>
  );
}
